org: olivvybee
app: orbit
service: orbit-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2

functions:
  fetch-twitter-data:
    handler: fetch-twitter-data.handler
    timeout: 10
    memorySize: 256
    environment:
      TWITTER_BEARER_TOKEN: ${ssm:/orbit/twitter-bearer-token}
    events:
      - httpApi:
          path: /fetch-twitter-data
          method: get

plugins:
  - serverless-esbuild
  - serverless-offline
